from fpdf import FPDF
import re


def clean_text(text: str) -> str:
    if not text:
        return ""

    # remove markdown formatting (keep headings text)
    text = text.replace("**", "")
    text = re.sub(r"[*_`>#]", "", text)

    # normalize bullets/dashes
    text = text.replace("•", "-")
    text = text.replace("–", "-").replace("—", "-")

    # remove emojis/unicode for core fonts
    text = text.encode("ascii", "ignore").decode("ascii")
    text = text.replace("\xa0", " ")

    return text.strip()


def break_extreme_tokens(line: str, max_token_len: int = 60) -> str:
    """
    Only break extremely long tokens (e.g., URLs) so fpdf doesn't crash.
    DOES NOT break normal words -> avoids ugly PDF.
    """
    parts = line.split(" ")
    fixed = []
    for p in parts:
        if len(p) > max_token_len:
            p = "\n".join([p[i:i+max_token_len] for i in range(0, len(p), max_token_len)])
        fixed.append(p)
    return " ".join(fixed)


def generate_pdf_bytes(title: str, content: str) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Arial", style="B", size=18)
    pdf.multi_cell(0, 10, clean_text(title), align="C")
    pdf.ln(2)

    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, "Generated by AI Travel Planner", align="C")
    pdf.ln(8)

    # Body
    lines = clean_text(content).split("\n")

    for raw in lines:
        line = break_extreme_tokens(raw.strip())

        if not line:
            pdf.ln(3)
            continue

        # Section headings
        if line.startswith("## "):
            heading = line.replace("## ", "").strip()
            pdf.ln(3)
            pdf.set_font("Arial", style="B", size=14)
            pdf.multi_cell(0, 8, heading)
            pdf.ln(1)
            continue

        # Day headings
        if re.match(r"^Day\s+\d+\s*:", line):
            pdf.ln(1)
            pdf.set_font("Arial", style="B", size=12)
            pdf.multi_cell(0, 7, line)
            pdf.ln(1)
            continue

        # Bullet points
        if line.startswith("- "):
            pdf.set_font("Arial", size=11)
            pdf.multi_cell(0, 6, "• " + line[2:].strip())
            continue

        # Normal paragraph
        pdf.set_font("Arial", size=11)
        pdf.multi_cell(0, 6, line)

    out = pdf.output(dest="S")
    if isinstance(out, (bytes, bytearray)):
        return bytes(out)
    return out.encode("latin-1", "ignore")
