from fpdf import FPDF
import re


def clean_text(text: str) -> str:
    """
    Clean text for PDF safely:
    - keep timings like 9:00 AM
    - keep colons, brackets, hyphens
    - remove only problematic unicode/emojis
    - remove markdown symbols
    """
    if not text:
        return ""

    text = text.replace("**", "")
    text = text.replace("`", "")
    text = text.replace(">", "")

    text = text.replace("•", "-")
    text = text.replace("–", "-").replace("—", "-")

    text = text.encode("latin-1", "ignore").decode("latin-1")

    text = re.sub(r"[ \t]+", " ", text)

    return text.strip()


def break_extreme_tokens(line: str, max_len: int = 80) -> str:
    """
    Break very long unbroken strings (URLs/long words) so fpdf doesn't crash.
    DOES NOT break normal sentences -> prevents ugly mid-word breaks.
    """
    if not line:
        return ""

    parts = line.split(" ")
    out = []
    for p in parts:
        if len(p) > max_len:
            chunks = [p[i:i + max_len] for i in range(0, len(p), max_len)]
            out.append("\n".join(chunks))
        else:
            out.append(p)
    return " ".join(out)


def safe_multi_cell(pdf: FPDF, text: str, w: int = 180, h: int = 6):
    """
    Safe writer: if fpdf fails due to rare edge cases, write smaller chunks.
    """
    try:
        pdf.multi_cell(w, h, text)
    except Exception:

        for chunk in [text[i:i+60] for i in range(0, len(text), 60)]:
            pdf.multi_cell(w, h, chunk)


def generate_pdf_bytes(title: str, content: str) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Arial", style="B", size=16)
    safe_multi_cell(pdf, clean_text(title), w=180, h=9)
    pdf.ln(2)

    pdf.set_font("Arial", size=10)
    safe_multi_cell(pdf, "Generated by AI Travel Planner", w=180, h=6)
    pdf.ln(5)

    pdf.set_font("Arial", size=11)

    cleaned = clean_text(content)
    lines = cleaned.split("\n")

    for raw in lines:

        line = raw.rstrip()

        if not line.strip():
            pdf.ln(2)
            continue

        if line.strip().startswith("## "):
            heading = line.strip().replace("## ", "").strip()
            pdf.ln(3)
            pdf.set_font("Arial", style="B", size=13)
            safe_multi_cell(pdf, heading, w=180, h=8)
            pdf.set_font("Arial", size=11)
            continue

        if re.match(r"^Day\s+\d+\s*:", line.strip()):
            pdf.ln(2)
            pdf.set_font("Arial", style="B", size=12)
            safe_multi_cell(pdf, line.strip(), w=180, h=7)
            pdf.set_font("Arial", size=11)
            continue

        if line.lstrip().startswith("- "):
            bullet_text = "- " + line.lstrip()[2:].strip()
            bullet_text = break_extreme_tokens(bullet_text, max_len=80)
            safe_multi_cell(pdf, bullet_text, w=180, h=6)
            continue

        line = break_extreme_tokens(line, max_len=80)
        safe_multi_cell(pdf, line, w=180, h=6)

    out = pdf.output(dest="S")
    if isinstance(out, (bytes, bytearray)):
        return bytes(out)
    return out.encode("latin-1", "ignore")
