from fpdf import FPDF
import re


def clean_text(text: str) -> str:
    if not text:
        return ""
    
    text = text.replace("**", "")
    text = re.sub(r"[*_`>#]", "", text)

    text = text.replace("–", "-").replace("—", "-")

    text = text.encode("ascii", "ignore").decode("ascii")

    text = text.replace("\xa0", " ")

    return text.strip()


def break_extreme_unbroken_strings(line: str, max_len: int = 70) -> str:

    if not line:
        return ""

    parts = line.split(" ")
    fixed_parts = []

    for p in parts:
        if len(p) > max_len:
            chunks = [p[i:i + max_len] for i in range(0, len(p), max_len)]
            fixed_parts.append("\n".join(chunks))
        else:
            fixed_parts.append(p)

    return " ".join(fixed_parts)


def safe_write(pdf: FPDF, text: str, w: int = 180, h: int = 6):
    try:
        pdf.multi_cell(w, h, text)
    except Exception:
        for chunk in [text[i:i+50] for i in range(0, len(text), 50)]:
            pdf.multi_cell(w, h, chunk)


def generate_pdf_bytes(title: str, content: str) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Arial", style="B", size=16)
    safe_write(pdf, clean_text(title), w=180, h=9)
    pdf.ln(2)

    pdf.set_font("Arial", size=10)
    safe_write(pdf, "Generated by AI Travel Planner", w=180, h=6)
    pdf.ln(5)

    pdf.set_font("Arial", size=11)

    content = clean_text(content)
    lines = content.split("\n")

    for raw in lines:
        line = raw.strip()

        if not line:
            pdf.ln(2)
            continue

        line = break_extreme_unbroken_strings(line, max_len=70)

        if line.startswith("## "):
            heading = line[3:].strip()
            pdf.ln(3)
            pdf.set_font("Arial", style="B", size=13)
            safe_write(pdf, heading, w=180, h=8)
            pdf.set_font("Arial", size=11)
            pdf.ln(1)
            continue

        if re.match(r"^Day\s+\d+\s*:", line):
            pdf.ln(2)
            pdf.set_font("Arial", style="B", size=12)
            safe_write(pdf, line, w=180, h=7)
            pdf.set_font("Arial", size=11)
            continue

        if line.startswith("- "):
            safe_write(pdf, "- " + line[2:].strip(), w=180, h=6)
            continue

        safe_write(pdf, line, w=180, h=6)

    out = pdf.output(dest="S")
    if isinstance(out, (bytes, bytearray)):
        return bytes(out)
    return out.encode("latin-1", "ignore")
